kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: application
  name: db-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

