kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume
  namespace: application
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kube_demo"

