apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
  namespace: application
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end-app
        image: wordpress
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-environment
              key: DB_HOST
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASSWORD
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_DATABASE
        resources:  # necessary for HPA
          requests:
            cpu: 0.5 # or 500m (specify a lower # if less resources available on host) 
            memory: 100Mi
          limits:
            cpu: 1.  # or 1000m
            memory: 150Mi
