kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: app-db
  namespace: application
  labels:
    app: app-db
spec:
  serviceName: app-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: app-db
    spec:
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-pv-claim
      containers:
      - name: app-db
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
          - name: db-volume  
            mountPath: /var/lib/mysql          