apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: app-db
  labels:
    domainName: app-db.application
spec:
  type: ClusterIP #default
  ports:
  - name: http
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: app-db
