apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: front-end-service
  labels:
    domainName: front-end.application
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: front-end
